apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-consumer-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1  # Optional. Default: apps/v1
    kind: Deployment       # Optional. Default: Deployment
    name: kafka-consumer        # Mandatory. Must be in the same namespace as the ScaledObject
           # Optional. Default: .spec.template.spec.containers[0]
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: kafka-broker.iterable.svc.cluster.local:9092
        consumerGroup: test-group
        topic: "quickstart-events"
        lagThreshold: '5'
        offsetResetPolicy: latest
        allowIdleConsumers: "false"
        scaleToZeroOnInvalidOffset: "true"
        version: 1.0.0 
    