apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-scaledobject
  namespace: iterable
  labels:
    deploymentName: kafka-consumer
spec:
  scaleTargetRef:
    name: kafka-consumer
  pollingInterval: 30
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: kafka-broker.iterable.svc.cluster.local:9092
        consumerGroup: test-group
        topic: "quickstart-events"
        lagThreshold: "5"
        offsetResetPolicy: latest