apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: consumer-scaler
  namespace: iterable
spec:
  scaleTargetRef:
    name: kafka-consumer
  pollingInterval: 15
  cooldownPeriod: 100
  maxReplicaCount: 10
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: kafka-broker.iterable.svc.cluster.local:9092
        consumerGroup: test-group
        topic: "quickstart-events"
        lagThreshold: "5"
        offsetResetPolicy: latest