apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: consumer-scaler
  namespace: default
spec:
  scaleTargetRef:
    deploymentName: kafka-consumer
  pollingInterval: 15
  cooldownPeriod: 100
  maxReplicaCount: 10
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: kafka-broker.iterable.svc.cluster.local:9092
        consumerGroup: test-group
        topic: "quickstart-events"
        lagThreshold: "5"
        offsetResetPolicy: latest